export const WEBSOCKET_URL =
  process.env.WEBSOCKET_URL || 'wss://dev.numberless.tech/ws';
const BASE_URL = process.env.BASE_URL || 'https://dev.numberless.tech';
const REPORTING_RESOURCE = BASE_URL + '/report';
export const LINE_MESSAGE_REPORTING_RESOURCE = REPORTING_RESOURCE + '/line';
export const GROUP_MESSAGE_REPORTING_RESOURCE = REPORTING_RESOURCE + '/group';
const MANAGEMENT_BASE_URL = BASE_URL + '/management';
export const POLICY_ACCEPTANCE = MANAGEMENT_BASE_URL + '/policy-acceptance';
const MESSAGING_BASE_URL = BASE_URL + '/messaging';
export const INITIAL_POST_MANAGEMENT_RESOURCE = MANAGEMENT_BASE_URL + '/user';
export const AUTH_SERVER_CHALLENGE_RESOURCE = BASE_URL + '/auth/user';
export const PERMISSION_MANAGEMENT_URL = MANAGEMENT_BASE_URL + '/permissions';
export const LINE_LINKS_MANAGEMENT_RESOURCE =
  MANAGEMENT_BASE_URL + '/line-links';
export const LINE_MANAGEMENT_RESOURCE = MANAGEMENT_BASE_URL + '/line';
export const LINE_RETRY_URL = LINE_MANAGEMENT_RESOURCE + '/retry';
export const DIRECT_MESSAGING_RESOURCE = MESSAGING_BASE_URL + '/line';
export const BUNDLE_MANAGEMENT_RESOURCE = MANAGEMENT_BASE_URL + '/bundle';
export const LARGE_FILE_PRESIGNED_URL_RESOURCE = BASE_URL + '/multimedia';
export const GROUP_MANAGEMENT_RESOURCE = MANAGEMENT_BASE_URL + '/group';
export const GROUP_LINKS_MANAGEMENT_RESOURCE =
  MANAGEMENT_BASE_URL + '/group-links';
export const GROUP_MESSAGING_RESOURCE = MESSAGING_BASE_URL + '/message';
export const QUEUE_GET_URL = MESSAGING_BASE_URL + '/queue';
export const BUG_REPORTING_ENDPOINT = BASE_URL + '/bugs';
export const BUNDLE_ID_PREPEND_LINK = 'https://porting.me/?bundleId=';

/**
 * Superport routes
 */
export const LINE_SUPERPORT_MANAGEMENT_RESOURCE =
  MANAGEMENT_BASE_URL + '/superport';
export const LINE_SUPERPORT_CREATION_DELETION =
  LINE_SUPERPORT_MANAGEMENT_RESOURCE + '/line';
export const LINE_SUPERPORT_LIMIT_MODIFICATION =
  LINE_SUPERPORT_MANAGEMENT_RESOURCE + '/limit';
export const LINE_SUPERPORT_PAUSE =
  LINE_SUPERPORT_MANAGEMENT_RESOURCE + '/pause';
export const LINE_SUPERPORT_RESUME =
  LINE_SUPERPORT_MANAGEMENT_RESOURCE + '/resume';
export const LINE_SUPERPORT_BULK_UPDATE =
  LINE_SUPERPORT_MANAGEMENT_RESOURCE + '/bulk-update';

/**
 * Contact port routes
 */
export const CONTACT_SHARING_MANAGEMENT_RESOURCE =
  MANAGEMENT_BASE_URL + '/contact-sharing';
export const CONTACT_SHARING_TICKET_MANAGEMENT =
  CONTACT_SHARING_MANAGEMENT_RESOURCE + '/ticket';
export const CONTACT_SHARING_PAUSE =
  CONTACT_SHARING_MANAGEMENT_RESOURCE + '/pause';
export const CONTACT_SHARING_RESUME =
  CONTACT_SHARING_MANAGEMENT_RESOURCE + '/resume';
