import axios from 'axios';
import {INITIAL_POST_MANAGEMENT_RESOURCE} from '@configs/api';

/**
 * part of the profile info that the server is responsible for generating.
 */
export interface ProfileServerGenerated {
  clientId: string;
}

/**
 * Posts user pubKey and receives serverKey and clientId in response.
 * @param {string} publicKey - url-safe base64 encoded public key of the user
 * @throws {Error} - If there is an issue posting user key or in the response
 * @returns {ProfileServerGenerated} - serverKey and clientId generated by the server.
 */
export async function submitUserPublicKey(
  publicKey: string,
): Promise<ProfileServerGenerated> {
  const response = await axios.post(INITIAL_POST_MANAGEMENT_RESOURCE, {
    authPubKey: publicKey,
  });
  if (response.data.userId) {
    const serverGenerated: ProfileServerGenerated = {
      clientId: response.data.userId,
    };
    return serverGenerated;
  }
  throw new Error('ProfilePostAPIError');
}
